I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigame.rpy", line 192, in script
    python:
  File "game/minigame.rpy", line 228, in <module>
    test = N.index(b'[HitObjects]\r\n') + 1
ValueError: b'[HitObjects]\r\n' is not in list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigame.rpy", line 192, in script
    python:
  File "A:\renpy-8.1.2-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "A:\renpy-8.1.2-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/minigame.rpy", line 228, in <module>
    test = N.index(b'[HitObjects]\r\n') + 1
ValueError: b'[HitObjects]\r\n' is not in list

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
Kilohertz 1.0
Mon Nov 27 11:18:47 2023
